url: "https://wwingyou.github.io" # the base hostname & protocol for your site, e.g. http://example.com
baseurl: "" # the subpath of your site, e.g. /blog
title: "My Blog" # the name of your site, e.g. ACME Corp.
plugins:
  - jekyll-paginate
paginate: 10
paginate_path: "/blog/page:num"
